/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.LaporanDao;
import dao.PasienDao;
import dao.DokterDao;
import model.Pasien;
import model.Dokter;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.sql.Date;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;

/**
 *
 * @author VanZ
 */
public class FormLaporan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLaporan.class.getName());

    private final LaporanDao laporanDao = new LaporanDao();
    private final PasienDao pasienDao = new PasienDao();
    private final DokterDao dokterDao = new DokterDao();

    private static final SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd");
    private static final NumberFormat RUPIAH = NumberFormat.getInstance(new Locale("in", "ID"));

    /**
     * Creates new form FormLaporan
     */
    public FormLaporan() {
        initComponents();
        setupTambahan();
        sesuaikanUkuranJendela();
    }

    /**
     * Membatasi ukuran jendela agar tidak melebihi layar (form ini cukup
     * panjang secara vertikal). Karena seluruh isi form sudah dibungkus
     * mainScrollPane, bagian yang terpotong tetap bisa dijangkau lewat
     * scrollbar.
     */
    private void sesuaikanUkuranJendela() {
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int width = Math.min(1150, screenSize.width - 60);
        int height = Math.min(750, screenSize.height - 80);
        setSize(width, height);
        setMinimumSize(new java.awt.Dimension(700, 400));
        setLocationRelativeTo(null);
    }

    /**
     * Wiring tambahan yang tidak dibuat oleh GUI builder:
     * - tooltip format tanggal
     * - listener export untuk tombol yang belum terhubung (jButton4, jButton6, jButton8)
     * - double click pada tabel riwayat pasien untuk melihat riwayat lengkap
     */
    private void setupTambahan() {
        String tipTanggal = "Format: yyyy-MM-dd (boleh dikosongkan)";
        txtAwal1.setToolTipText(tipTanggal);
        txtAkhir1.setToolTipText(tipTanggal);
        txtAwal2.setToolTipText(tipTanggal);
        txtAkhir2.setToolTipText(tipTanggal);
        txtAwal3.setToolTipText(tipTanggal);
        txtAkhir3.setToolTipText(tipTanggal);
        txtDokter1.setToolTipText("ID atau nama dokter (boleh dikosongkan)");
        txtstatus1.setToolTipText("Status kunjungan, contoh: selesai / menunggu / batal (boleh dikosongkan)");
        txtAwal4.setToolTipText("Masukkan ID Pasien atau sebagian nama pasien");
        txtAkhir4.setToolTipText("Tidak digunakan pada pencarian ini");
        txtAkhir4.setEnabled(false);

        jButton4.addActionListener(evt -> exportTableToCsv(tbl2, "laporan_pendapatan"));
        jButton6.addActionListener(evt -> exportTableToCsv(tbl3, "laporan_obat_terpakai"));
        jButton8.addActionListener(evt -> exportTableToCsv(tbl4, "hasil_pencarian_pasien"));

        tbl4.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int row = tbl4.getSelectedRow();
                    if (row >= 0) {
                        int idPasien = Integer.parseInt(String.valueOf(tbl4.getValueAt(row, 0)));
                        String nama = String.valueOf(tbl4.getValueAt(row, 1));
                        tampilkanRiwayatLengkap(idPasien, nama);
                    }
                }
            }
        });
        lblTotal4.setText("Ketikkan ID/nama pasien lalu klik \"Cari Pasien\". Klik dua kali baris hasil untuk melihat riwayat lengkap.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        mainScrollPane = new javax.swing.JScrollPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAwal1 = new javax.swing.JTextField();
        txtAkhir1 = new javax.swing.JTextField();
        txtDokter1 = new javax.swing.JTextField();
        txtstatus1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblTotal1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAwal2 = new javax.swing.JTextField();
        txtAkhir2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        lblTotal2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAwal3 = new javax.swing.JTextField();
        txtAkhir3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl3 = new javax.swing.JTable();
        lblTotal3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtAwal4 = new javax.swing.JTextField();
        txtAkhir4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl4 = new javax.swing.JTable();
        lblTotal4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("F O R M U L I R   L A P O R A N");

        jLabel2.setText("Dari:");

        jLabel3.setText("Sampai:");

        jLabel4.setText("Dokter:");

        jLabel5.setText("Status:");

        txtAkhir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAkhir1ActionPerformed(evt);
            }
        });

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Kunjungan", "Tanggal", "Nama Pasien", "Nama Dokter", "Keluhan", "Status"
            }
        ));
        jScrollPane1.setViewportView(tbl1);

        jButton1.setText("Tampilkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Export");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Kunjungan Per Periode");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Pendapatan Per Periode");

        jLabel8.setText("Dari:");

        jLabel9.setText("Sampai:");

        txtAkhir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAkhir2ActionPerformed(evt);
            }
        });

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID bayar", "Tanggal Bayar", "Nama Pasien", "Metode Bayar", "Biaya Tindakan", "Biaya Obat", "Total Bayar"
            }
        ));
        jScrollPane2.setViewportView(tbl2);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Pendapatan Per Periode");

        jLabel11.setText("Dari(Tanggal Kunjungan):");

        jLabel13.setText("Sampai:");

        txtAkhir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAkhir3ActionPerformed(evt);
            }
        });

        jButton3.setText("Tampilkan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Export");

        tbl3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Obat", "Nama Obat", "Satuan", "Total Terpakai", "Total Nilai (RP)"
            }
        ));
        jScrollPane3.setViewportView(tbl3);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Riwayat Pasien");

        jButton5.setText("Tampilkan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Export");

        jLabel15.setText("Cari ID/Nama Pasien:");

        jLabel16.setText("Sampai:");

        txtAkhir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAkhir4ActionPerformed(evt);
            }
        });

        jButton7.setText("Cari Pasien");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Export");

        tbl4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pasien", "Nama Pasien", "Jenis Kelamin", "Alamat"
            }
        ));
        jScrollPane4.setViewportView(tbl4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(lblTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(lblTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(lblTotal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAwal1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAkhir1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDokter1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAwal2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAkhir2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAwal3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAkhir3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAwal4, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAkhir4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8))
                            .addComponent(jScrollPane4)
                            .addComponent(lblTotal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtAwal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAkhir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDokter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtAwal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAkhir2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(txtAwal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAkhir3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(txtAwal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAkhir4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        mainScrollPane.setViewportView(pnlContent);
        mainScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        mainScrollPane.getHorizontalScrollBar().setUnitIncrement(16);

        javax.swing.GroupLayout frameLayout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(frameLayout);
        frameLayout.setHorizontalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        frameLayout.setVerticalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAkhir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAkhir1ActionPerformed
        tampilkanLaporanKunjungan();
    }//GEN-LAST:event_txtAkhir1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tampilkanLaporanKunjungan();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAkhir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAkhir2ActionPerformed
        tampilkanLaporanPendapatan();
    }//GEN-LAST:event_txtAkhir2ActionPerformed

    private void txtAkhir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAkhir3ActionPerformed
        tampilkanLaporanObatTerpakai();
    }//GEN-LAST:event_txtAkhir3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tampilkanLaporanPendapatan();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        exportTableToCsv(tbl1, "laporan_kunjungan");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        tampilkanLaporanObatTerpakai();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtAkhir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAkhir4ActionPerformed
        cariRiwayatPasien();
    }//GEN-LAST:event_txtAkhir4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        cariRiwayatPasien();
    }//GEN-LAST:event_jButton7ActionPerformed

    // =====================================================================
    // 1. LAPORAN KUNJUNGAN PER PERIODE
    // =====================================================================
    private void tampilkanLaporanKunjungan() {
        try {
            Date awal = parseTanggal(txtAwal1.getText());
            Date akhir = parseTanggal(txtAkhir1.getText());
            Integer idDokter = resolveIdDokter(txtDokter1.getText());
            String status = txtstatus1.getText() == null ? "" : txtstatus1.getText().trim();

            List<Object[]> data = laporanDao.getKunjunganPerPeriode(awal, akhir, idDokter, status);
            DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
            model.setRowCount(0);
            for (Object[] row : data) {
                model.addRow(row);
            }
            lblTotal1.setText("Total Kunjungan: " + data.size());
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Validasi", JOptionPane.WARNING_MESSAGE);
        }
    }

    // =====================================================================
    // 2. LAPORAN PENDAPATAN PER PERIODE
    // =====================================================================
    private void tampilkanLaporanPendapatan() {
        try {
            String awal = txtAwal2.getText() == null ? "" : txtAwal2.getText().trim();
            String akhir = txtAkhir2.getText() == null ? "" : txtAkhir2.getText().trim();
            if (!awal.isEmpty()) {
                parseTanggal(awal);
            }
            if (!akhir.isEmpty()) {
                parseTanggal(akhir);
            }

            List<Object[]> data = laporanDao.getPendapatanPerPeriode(awal, akhir);
            DefaultTableModel model = (DefaultTableModel) tbl2.getModel();
            model.setRowCount(0);
            for (Object[] row : data) {
                model.addRow(new Object[]{
                    row[0], row[1], row[2], row[3],
                    formatRupiah((BigDecimal) row[4]),
                    formatRupiah((BigDecimal) row[5]),
                    formatRupiah((BigDecimal) row[6])
                });
            }
            BigDecimal[] total = laporanDao.getTotalPendapatan(awal, akhir);
            lblTotal2.setText("Total Tindakan: " + formatRupiah(total[0])
                    + "   |   Total Obat: " + formatRupiah(total[1])
                    + "   |   Total Pendapatan: " + formatRupiah(total[2]));
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Validasi", JOptionPane.WARNING_MESSAGE);
        }
    }

    // =====================================================================
    // 3. LAPORAN OBAT TERPAKAI (berdasarkan resep_detail)
    // =====================================================================
    private void tampilkanLaporanObatTerpakai() {
        try {
            Date awal = parseTanggal(txtAwal3.getText());
            Date akhir = parseTanggal(txtAkhir3.getText());

            List<Object[]> data = laporanDao.getObatTerpakai(awal, akhir);
            DefaultTableModel model = (DefaultTableModel) tbl3.getModel();
            model.setRowCount(0);
            int totalItem = 0;
            BigDecimal totalNilai = BigDecimal.ZERO;
            for (Object[] row : data) {
                model.addRow(new Object[]{
                    row[0], row[1], row[2], row[3], formatRupiah((BigDecimal) row[4])
                });
                totalItem += (Integer) row[3];
                totalNilai = totalNilai.add((BigDecimal) row[4]);
            }
            lblTotal3.setText("Total Obat Terpakai: " + totalItem + " unit   |   Total Nilai: " + formatRupiah(totalNilai));
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Validasi", JOptionPane.WARNING_MESSAGE);
        }
    }

    // =====================================================================
    // 4. RIWAYAT PASIEN (kunjungan + pemeriksaan + resep + pembayaran)
    // =====================================================================
    private void cariRiwayatPasien() {
        String keyword = txtAwal4.getText() == null ? "" : txtAwal4.getText().trim();
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan ID atau nama pasien terlebih dahulu.",
                    "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        List<Pasien> data = pasienDao.cariPasien(keyword);
        DefaultTableModel model = (DefaultTableModel) tbl4.getModel();
        model.setRowCount(0);
        for (Pasien p : data) {
            model.addRow(new Object[]{p.getIdPasien(), p.getNamaPasien(), p.getJk(), p.getAlamat()});
        }
        lblTotal4.setText("Total Pasien Ditemukan: " + data.size() + " (klik dua kali baris untuk lihat riwayat lengkap)");
        if (data.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data pasien tidak ditemukan.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * Menampilkan dialog berisi riwayat lengkap seorang pasien:
     * kunjungan -&gt; pemeriksaan -&gt; resep -&gt; resep_detail (obat) -&gt; pembayaran.
     */
    private void tampilkanRiwayatLengkap(int idPasien, String namaPasien) {
        List<Object[]> listKunjungan = laporanDao.getKunjunganByPasien(idPasien);
        StringBuilder sb = new StringBuilder();
        sb.append("RIWAYAT LENGKAP PASIEN\n");
        sb.append("ID Pasien : ").append(idPasien).append("\n");
        sb.append("Nama      : ").append(namaPasien).append("\n");
        sb.append("========================================================\n\n");

        if (listKunjungan.isEmpty()) {
            sb.append("Belum ada riwayat kunjungan untuk pasien ini.\n");
        }

        int no = 1;
        for (Object[] kj : listKunjungan) {
            int idKunjungan = (Integer) kj[0];
            sb.append(no++).append(". Kunjungan #").append(idKunjungan).append("\n");
            sb.append("   Tanggal   : ").append(kj[1]).append("\n");
            sb.append("   Dokter    : ").append(kj[2]).append("\n");
            sb.append("   Keluhan   : ").append(kj[3]).append("\n");
            sb.append("   Status    : ").append(kj[4]).append("\n");

            Object[] pemeriksaan = laporanDao.getPemeriksaanByKunjungan(idKunjungan);
            if (pemeriksaan != null) {
                int idPemeriksaan = (Integer) pemeriksaan[0];
                sb.append("   -- Pemeriksaan --\n");
                sb.append("   Diagnosa       : ").append(pemeriksaan[1]).append("\n");
                sb.append("   Tindakan       : ").append(pemeriksaan[2]).append("\n");
                sb.append("   Catatan        : ").append(pemeriksaan[3]).append("\n");
                sb.append("   Biaya Tindakan : ").append(formatRupiah((BigDecimal) pemeriksaan[4])).append("\n");

                List<Object[]> listResep = laporanDao.getResepByPemeriksaan(idPemeriksaan);
                if (listResep.isEmpty()) {
                    sb.append("   -- Resep : (tidak ada resep) --\n");
                }
                for (Object[] rs : listResep) {
                    int idResep = (Integer) rs[0];
                    sb.append("   -- Resep #").append(idResep).append(" (tgl ").append(rs[1]).append(") --\n");
                    List<Object[]> detail = laporanDao.getResepDetailByResep(idResep);
                    if (detail.isEmpty()) {
                        sb.append("      (tidak ada detail obat)\n");
                    }
                    for (Object[] d : detail) {
                        sb.append("      * ").append(d[0]).append(" - ").append(d[1]).append(" ").append(d[2])
                                .append(" (").append(d[3]).append(") @ ").append(formatRupiah((BigDecimal) d[4]))
                                .append(" = ").append(formatRupiah((BigDecimal) d[5])).append("\n");
                    }
                }
            } else {
                sb.append("   -- Pemeriksaan : (belum diperiksa) --\n");
            }

            Object[] bayar = laporanDao.getPembayaranByKunjungan(idKunjungan);
            if (bayar != null) {
                sb.append("   -- Pembayaran --\n");
                sb.append("   ID Bayar        : ").append(bayar[0]).append("\n");
                sb.append("   Tanggal Bayar   : ").append(bayar[1]).append("\n");
                sb.append("   Metode Bayar    : ").append(bayar[2]).append("\n");
                sb.append("   Biaya Tindakan  : ").append(formatRupiah((BigDecimal) bayar[3])).append("\n");
                sb.append("   Biaya Obat      : ").append(formatRupiah((BigDecimal) bayar[4])).append("\n");
                sb.append("   Total Bayar     : ").append(formatRupiah((BigDecimal) bayar[5])).append("\n");
                sb.append("   Kode Pembayaran : ").append(bayar[6]).append("\n");
            } else {
                sb.append("   -- Pembayaran : (belum dibayar) --\n");
            }
            sb.append("\n");
        }

        String isiRiwayat = sb.toString();

        JTextArea area = new JTextArea(isiRiwayat);
        area.setEditable(false);
        area.setFont(new Font("Monospaced", Font.PLAIN, 12));
        area.setCaretPosition(0);
        JScrollPane scroll = new JScrollPane(area);
        scroll.setPreferredSize(new Dimension(620, 500));

        JDialog dialog = new JDialog(this, "Riwayat Lengkap - " + namaPasien, true);
        dialog.setLayout(new BorderLayout());
        dialog.add(scroll, BorderLayout.CENTER);

        JButton btnExport = new JButton("Export ke .txt");
        btnExport.addActionListener(evt -> exportTextToFile(isiRiwayat, "riwayat_pasien_" + idPasien));
        JPanel panelBtn = new JPanel();
        panelBtn.add(btnExport);
        dialog.add(panelBtn, BorderLayout.SOUTH);

        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    // =====================================================================
    // UTILITAS
    // =====================================================================

    /** Parse teks tanggal (format yyyy-MM-dd). Mengembalikan null jika kosong. */
    private Date parseTanggal(String input) {
        if (input == null || input.trim().isEmpty()) {
            return null;
        }
        try {
            return Date.valueOf(input.trim());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Format tanggal salah: \"" + input.trim() + "\". Gunakan format yyyy-MM-dd, contoh: 2025-01-31.");
        }
    }

    /**
     * Mengubah isi txtDokter1 menjadi id_dokter. Boleh diisi angka (ID) atau
     * sebagian nama dokter. Mengembalikan null jika input kosong (artinya:
     * semua dokter).
     */
    private Integer resolveIdDokter(String input) {
        if (input == null || input.trim().isEmpty()) {
            return null;
        }
        String value = input.trim();
        if (value.matches("\\d+")) {
            return Integer.parseInt(value);
        }
        List<Dokter> hasil = dokterDao.cariDokter(value);
        if (hasil.isEmpty()) {
            throw new IllegalArgumentException("Dokter dengan ID/nama \"" + value + "\" tidak ditemukan.");
        }
        return hasil.get(0).getIdDokter();
    }

    private String formatRupiah(BigDecimal value) {
        if (value == null) {
            value = BigDecimal.ZERO;
        }
        return "Rp " + RUPIAH.format(value);
    }

    /** Export isi sebuah JTable (berdasarkan DefaultTableModel-nya) ke file CSV. */
    private void exportTableToCsv(JTable table, String namaDasarFile) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tidak ada data untuk diexport. Tampilkan data terlebih dahulu.",
                    "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        JFileChooser chooser = new JFileChooser();
        chooser.setSelectedFile(new File(namaDasarFile + "_" + SDF.format(new java.util.Date()) + ".csv"));
        int hasil = chooser.showSaveDialog(this);
        if (hasil != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File file = chooser.getSelectedFile();
        try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
            for (int c = 0; c < model.getColumnCount(); c++) {
                pw.print(csvEscape(model.getColumnName(c)));
                if (c < model.getColumnCount() - 1) {
                    pw.print(",");
                }
            }
            pw.println();
            for (int r = 0; r < model.getRowCount(); r++) {
                for (int c = 0; c < model.getColumnCount(); c++) {
                    Object val = model.getValueAt(r, c);
                    pw.print(csvEscape(val == null ? "" : val.toString()));
                    if (c < model.getColumnCount() - 1) {
                        pw.print(",");
                    }
                }
                pw.println();
            }
            JOptionPane.showMessageDialog(this, "Data berhasil diexport ke:\n" + file.getAbsolutePath());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Gagal export data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exportTextToFile(String content, String namaDasarFile) {
        JFileChooser chooser = new JFileChooser();
        chooser.setSelectedFile(new File(namaDasarFile + ".txt"));
        int hasil = chooser.showSaveDialog(this);
        if (hasil != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File file = chooser.getSelectedFile();
        try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
            pw.print(content);
            JOptionPane.showMessageDialog(this, "Riwayat berhasil diexport ke:\n" + file.getAbsolutePath());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Gagal export riwayat: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String csvEscape(String s) {
        if (s.contains(",") || s.contains("\"") || s.contains("\n")) {
            return "\"" + s.replace("\"", "\"\"") + "\"";
        }
        return s;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLaporan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JLabel lblTotal3;
    private javax.swing.JLabel lblTotal4;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    private javax.swing.JTable tbl3;
    private javax.swing.JTable tbl4;
    private javax.swing.JTextField txtAkhir1;
    private javax.swing.JTextField txtAkhir2;
    private javax.swing.JTextField txtAkhir3;
    private javax.swing.JTextField txtAkhir4;
    private javax.swing.JTextField txtAwal1;
    private javax.swing.JTextField txtAwal2;
    private javax.swing.JTextField txtAwal3;
    private javax.swing.JTextField txtAwal4;
    private javax.swing.JTextField txtDokter1;
    private javax.swing.JTextField txtstatus1;
    // End of variables declaration//GEN-END:variables
}
